name: run test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
        
      - name: 'Setup Chrome and chromedriver'
        run: |
              sudo apt-get install xvfb
              sudo apt-get install unzip
              CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
              sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
              sudo apt-get update 
              sudo apt install google-chrome-stable
              wget -N http://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
              unzip chromedriver_linux64.zip
              chmod +x chromedriver
              sudo mv -f chromedriver /usr/local/bin/
